Change zsh standard compatibility
zdharma-continuum/fast-syntax-highlighting pull request #11
Opened 2021-12-06 17:46 UTC by grigorii-horos

Function dir should be `/functions`, see: https://github.com/zdharma-continuum/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#funcs-dir

2021-12-06 18:07 UTC, alichtman commented
Ironically, this plug-in and the standard you linked were written by the same person :)

2021-12-06 23:52 UTC, alichtman commented
Let's also drop all Unicode chars in file names here.

2021-12-07 07:30 UTC, vladdoster commented
- [ ] Remove Unicode characters in file names

2021-12-07 07:32 UTC, vladdoster requested changes
@grigorii-horos

- [ ] Strip Unicode characters from filenames

2021-12-07 08:59 UTC, grigorii-horos commented
@vladdoster Done!

2021-12-07 14:10 UTC, alichtman approved these changes
LGTM. @pschmitt why the thumbs down?

2021-12-07 15:03 UTC, pschmitt commented
Renaming all the internal funcs is out of scope for this pr imo.

2021-12-08 01:30 UTC, alichtman commented
While that's true, I'm ok with a "modernize this repo" PR

2021-12-08 10:59 UTC, alichtman commented
@pschmitt Is right, now that I think about it. Let's split this into two PRs.

2022-01-17 23:01 UTC, alichtman commented
On second thought, this PR is now impossible to review efficiently.

2022-01-17 23:03 UTC, alichtman commented
Let's cherrypick `Remove Unicode symbol →` to a new PR and I'll approve this one.

2022-01-19 01:58 UTC, FranklinYu commented
If we were to change the function prefix, would we also want to change

https://github.com/zdharma-continuum/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#namespacing

as well? Currently it recommends `→` for hook functions. See also #4.

2022-01-21 13:33 UTC, grigorii-horos commented
Hey @alichtman Done!

2022-01-27 05:27 UTC, Aloxaf commented
I suggest not to remove the unicode prefix.

A unicode prefix is less likely to be a prefix of a normal function/file so that it is less likely to appear in the completion list.

The repo is deleted and I cannot find the old discussion, but the commit which change ascii prefix to unicode preifx is still here: https://github.com/zdharma-continuum/fast-syntax-highlighting/commit/a3242a93399535faccda4896ab5c61a7a6dca1fe

2022-02-11 21:56 UTC, vimpostor commented on .directory
> +[Dolphin]
In the first commit you deleted the Dolphin config and here you are readding it again by accident. Please remove it again from the second commit.

2022-02-28 03:25 UTC, vladdoster approved these changes
LGTM. Will squash the two commits on merge.

2022-02-28 03:30 UTC, vladdoster commented
On second thought, I just saw @alichtman comment regarding splitting up changes.

@grigorii-horos, Could you please split changes into two PRs to make the changes more atomic?

2022-02-28 03:32 UTC, vladdoster requested changes
- [ ] PR for renaming internal functions
- [ ] PR for using `/functions`

2022-11-06 11:32 UTC, closed without merging